use_frameworks!

platform :ios, '8.0'

target 'CocoaHTTPServer_Example' do
  pod 'CocoaHTTPServer', :path => '../'
  pod 'AFNetworking'
  target 'CocoaHTTPServer_Tests' do
    inherit! :search_paths

    
  end
end
